import {
  Lead,
  Campaign,
  Conversation,
  FollowUp,
  BusinessSettings,
} from '@/types';
import { BUSINESS_INFO, DEFAULT_AI_INSTRUCTIONS } from './constants';

export const MOCK_SUMMARY_METRICS = {
  totalLeads: 1248,
  contacted: 850,
  replies: 342,
  coldLeads: 420,
  warmLeads: 185,
  hotLeads: 43,
  activeCampaignName: 'Tamil Nadu Business Website Outreach - Q3',
  activeCampaignStatus: 'active' as const,
  replyRate: '40.2%',
  conversionRate: '5.1%',
};

export const MOCK_LEADS: Lead[] = [
  {
    id: 'lead-1',
    name: 'Arun Kumar',
    phone: '+91 98765 43210',
    business: 'Arun Textiles & Handlooms',
    category: 'Textile & Retail',
    status: 'qualified',
    temperature: 'hot',
    city: 'Coimbatore',
    lastMessageAt: '2026-08-09T18:45:00Z',
    lastReplyAt: '2026-08-09T18:42:00Z',
    nextFollowupAt: '2026-08-10T10:00:00Z',
    createdAt: '2026-08-01T09:00:00Z',
    updatedAt: '2026-08-09T18:45:00Z',
    notes: 'Urgent: Needs an e-commerce catalog landing page for upcoming festive sale.',
  },
  {
    id: 'lead-2',
    name: 'Priya Sundaram',
    phone: '+91 98765 43211',
    business: 'Priya Luxe Hair & Beauty Salon',
    category: 'Beauty & Wellness',
    status: 'replied',
    temperature: 'warm',
    city: 'Chennai',
    lastMessageAt: '2026-08-09T16:30:00Z',
    lastReplyAt: '2026-08-09T16:20:00Z',
    nextFollowupAt: '2026-08-11T11:30:00Z',
    createdAt: '2026-08-02T11:20:00Z',
    updatedAt: '2026-08-09T16:30:00Z',
    notes: 'Interested in booking appointments directly from portfolio website.',
  },
  {
    id: 'lead-3',
    name: 'Ravi Chandran',
    phone: '+91 98765 43212',
    business: 'Ravi Motors & Spares',
    category: 'Automobile',
    status: 'contacted',
    temperature: 'cold',
    city: 'Madurai',
    lastMessageAt: '2026-08-08T14:15:00Z',
    createdAt: '2026-08-03T14:00:00Z',
    updatedAt: '2026-08-08T14:15:00Z',
    notes: 'Initial WhatsApp outreach sent. Waiting for response.',
  },
  {
    id: 'lead-4',
    name: 'Karthik Subramanian',
    phone: '+91 98765 43213',
    business: 'Kovai Organic Foods',
    category: 'Food & Agriculture',
    status: 'qualified',
    temperature: 'hot',
    city: 'Coimbatore',
    lastMessageAt: '2026-08-09T19:10:00Z',
    lastReplyAt: '2026-08-09T19:05:00Z',
    nextFollowupAt: '2026-08-10T14:00:00Z',
    createdAt: '2026-08-04T10:15:00Z',
    updatedAt: '2026-08-09T19:10:00Z',
    notes: 'Wants full corporate website + product portfolio showcase.',
  },
  {
    id: 'lead-5',
    name: 'Meena Jayaram',
    phone: '+91 98765 43214',
    business: 'Salem Silk Exports',
    category: 'Textile & Manufacturing',
    status: 'replied',
    temperature: 'warm',
    city: 'Salem',
    lastMessageAt: '2026-08-09T12:00:00Z',
    lastReplyAt: '2026-08-09T11:45:00Z',
    nextFollowupAt: '2026-08-11T16:00:00Z',
    createdAt: '2026-08-05T08:30:00Z',
    updatedAt: '2026-08-09T12:00:00Z',
    notes: 'Asked about redesigning their 5-year-old legacy website.',
  },
  {
    id: 'lead-6',
    name: 'Suresh Babu',
    phone: '+91 98765 43215',
    business: 'Trichy Tech Solutions',
    category: 'IT & Consulting',
    status: 'converted',
    temperature: 'hot',
    city: 'Tiruchirappalli',
    lastMessageAt: '2026-08-07T15:20:00Z',
    lastReplyAt: '2026-08-07T15:00:00Z',
    createdAt: '2026-07-28T10:00:00Z',
    updatedAt: '2026-08-07T15:20:00Z',
    notes: 'Contract signed for Landing Page + Portfolio Website package.',
  },
  {
    id: 'lead-7',
    name: 'Anitha Ramesh',
    phone: '+91 98765 43216',
    business: 'Tanjore Handicrafts & Arts',
    category: 'Arts & Crafts',
    status: 'contacted',
    temperature: 'cold',
    city: 'Thanjavur',
    lastMessageAt: '2026-08-08T10:30:00Z',
    createdAt: '2026-08-06T12:00:00Z',
    updatedAt: '2026-08-08T10:30:00Z',
    notes: 'Sent introduction video and website audit offer.',
  },
  {
    id: 'lead-8',
    name: 'Vijay Anand',
    phone: '+91 98765 43217',
    business: 'Nellai Spices & Grocery',
    category: 'Retail & FMCG',
    status: 'replied',
    temperature: 'warm',
    city: 'Tirunelveli',
    lastMessageAt: '2026-08-09T17:50:00Z',
    lastReplyAt: '2026-08-09T17:40:00Z',
    nextFollowupAt: '2026-08-12T09:30:00Z',
    createdAt: '2026-08-06T15:00:00Z',
    updatedAt: '2026-08-09T17:50:00Z',
    notes: 'Requested quotation for local business landing page.',
  },
];

export const MOCK_CAMPAIGNS: Campaign[] = [
  {
    id: 'camp-1',
    name: 'Tamil Nadu Business Website Outreach - Q3',
    status: 'active',
    targetAudience: 'SMEs & Retailers in Coimbatore, Chennai, Madurai',
    totalTarget: 500,
    contacted: 412,
    replied: 168,
    hotLeads: 24,
    startTime: '2026-08-01T00:00:00Z',
    messageTemplate: 'Hi {{name}}, we noticed {{business}} in {{city}} could gain 3x more customers with a modern business website. Check our recent portfolio at https://santhosh-portfolio-gamma.vercel.app/',
    createdAt: '2026-07-30T10:00:00Z',
  },
  {
    id: 'camp-2',
    name: 'Website Redesign Drive - Textile & Silk Industry',
    status: 'active',
    targetAudience: 'Textile exporters and weavers in Salem & Erode',
    totalTarget: 350,
    contacted: 280,
    replied: 114,
    hotLeads: 14,
    startTime: '2026-08-03T00:00:00Z',
    messageTemplate: 'Hello {{name}}! Give {{business}} a high-end digital storefront. Reliable Vision builds custom responsive websites tailored for textile exporters.',
    createdAt: '2026-08-02T14:00:00Z',
  },
  {
    id: 'camp-3',
    name: 'Beauty & Wellness Salon Landing Page Special',
    status: 'paused',
    targetAudience: 'Salons & Spas in Tier-1 & Tier-2 TN Cities',
    totalTarget: 200,
    contacted: 158,
    replied: 60,
    hotLeads: 5,
    startTime: '2026-07-15T00:00:00Z',
    endTime: '2026-07-31T00:00:00Z',
    messageTemplate: 'Hi {{name}}, showcase {{business}} treatments and accept online bookings effortlessly with our customized salon websites.',
    createdAt: '2026-07-14T09:00:00Z',
  },
  {
    id: 'camp-4',
    name: 'Automobile & Spares Business Portal Campaign',
    status: 'draft',
    targetAudience: 'Auto parts dealers in Trichy & Madurai',
    totalTarget: 198,
    contacted: 0,
    replied: 0,
    hotLeads: 0,
    startTime: '2026-08-15T00:00:00Z',
    messageTemplate: 'Greetings {{name}}, step up {{business}} with an online product catalog website.',
    createdAt: '2026-08-08T11:00:00Z',
  },
];

export const MOCK_CONVERSATIONS: Conversation[] = [
  {
    id: 'conv-1',
    leadId: 'lead-1',
    leadName: 'Arun Kumar',
    leadPhone: '+91 98765 43210',
    leadBusiness: 'Arun Textiles & Handlooms',
    category: 'Textile & Retail',
    temperature: 'hot',
    status: 'active',
    lastMessage: 'Can we schedule a phone call today to discuss the website proposal and timeline?',
    lastMessageTime: '2026-08-09T18:45:00Z',
    unreadCount: 1,
    needsHuman: true,
    messages: [
      {
        id: 'msg-101',
        leadId: 'lead-1',
        conversationId: 'conv-1',
        direction: 'outbound',
        message: 'Hi Arun! We noticed Arun Textiles in Coimbatore could double its customer inquiries with a high-converting business website. Take a look at our portfolio: https://santhosh-portfolio-gamma.vercel.app/',
        createdAt: '2026-08-09T18:00:00Z',
        isAiGenerated: true,
      },
      {
        id: 'msg-102',
        leadId: 'lead-1',
        conversationId: 'conv-1',
        direction: 'inbound',
        message: 'Hello! I saw your portfolio. We are launching our Diwali silk collection next month and urgently need a modern landing page for wholesale buyers.',
        createdAt: '2026-08-09T18:30:00Z',
        intent: 'website_inquiry',
      },
      {
        id: 'msg-103',
        leadId: 'lead-1',
        conversationId: 'conv-1',
        direction: 'outbound',
        message: 'That sounds fantastic! Reliable Vision specializes in fast, mobile-friendly landing pages and custom business websites. Would you like a catalog showcase layout?',
        createdAt: '2026-08-09T18:35:00Z',
        isAiGenerated: true,
      },
      {
        id: 'msg-104',
        leadId: 'lead-1',
        conversationId: 'conv-1',
        direction: 'inbound',
        message: 'Yes! Can we schedule a phone call today to discuss the website proposal and timeline?',
        createdAt: '2026-08-09T18:45:00Z',
        intent: 'request_call',
      },
    ],
  },
  {
    id: 'conv-2',
    leadId: 'lead-4',
    leadName: 'Karthik Subramanian',
    leadPhone: '+91 98765 43213',
    leadBusiness: 'Kovai Organic Foods',
    category: 'Food & Agriculture',
    temperature: 'hot',
    status: 'active',
    lastMessage: 'Please send your website packages and pricing details to our email.',
    lastMessageTime: '2026-08-09T19:10:00Z',
    unreadCount: 0,
    needsHuman: true,
    messages: [
      {
        id: 'msg-201',
        leadId: 'lead-4',
        conversationId: 'conv-2',
        direction: 'outbound',
        message: 'Hi Karthik, boost Kovai Organic Foods brand presence with a crisp corporate website developed by Reliable Vision | Web Studio.',
        createdAt: '2026-08-09T18:50:00Z',
        isAiGenerated: true,
      },
      {
        id: 'msg-202',
        leadId: 'lead-4',
        conversationId: 'conv-2',
        direction: 'inbound',
        message: 'Hi, what are your rates for a 5-page organic store business website?',
        createdAt: '2026-08-09T19:00:00Z',
        intent: 'pricing_inquiry',
      },
      {
        id: 'msg-203',
        leadId: 'lead-4',
        conversationId: 'conv-2',
        direction: 'inbound',
        message: 'Please send your website packages and pricing details to our email.',
        createdAt: '2026-08-09T19:10:00Z',
        intent: 'request_proposal',
      },
    ],
  },
  {
    id: 'conv-3',
    leadId: 'lead-2',
    leadName: 'Priya Sundaram',
    leadPhone: '+91 98765 43211',
    leadBusiness: 'Priya Luxe Hair & Beauty Salon',
    category: 'Beauty & Wellness',
    temperature: 'warm',
    status: 'active',
    lastMessage: 'Do you also provide website redesign for existing sites?',
    lastMessageTime: '2026-08-09T16:30:00Z',
    unreadCount: 0,
    needsHuman: false,
    messages: [
      {
        id: 'msg-301',
        leadId: 'lead-2',
        conversationId: 'conv-3',
        direction: 'outbound',
        message: 'Hi Priya, make booking salon appointments super easy for your clients with a sleek web studio site by Reliable Vision.',
        createdAt: '2026-08-09T16:00:00Z',
        isAiGenerated: true,
      },
      {
        id: 'msg-302',
        leadId: 'lead-2',
        conversationId: 'conv-3',
        direction: 'inbound',
        message: 'Do you also provide website redesign for existing sites?',
        createdAt: '2026-08-09T16:30:00Z',
        intent: 'service_inquiry',
      },
    ],
  },
];

export const MOCK_FOLLOWUPS: FollowUp[] = [
  {
    id: 'fol-1',
    leadId: 'lead-1',
    leadName: 'Arun Kumar',
    leadPhone: '+91 98765 43210',
    leadBusiness: 'Arun Textiles & Handlooms',
    scheduledAt: '2026-08-10T10:00:00Z',
    followupNumber: 1,
    status: 'pending',
    messageTemplate: 'Hi Arun, following up regarding the e-commerce landing page call for Arun Textiles. Let us know what time works best today!',
    temperature: 'hot',
    createdAt: '2026-08-09T18:45:00Z',
  },
  {
    id: 'fol-2',
    leadId: 'lead-4',
    leadName: 'Karthik Subramanian',
    leadPhone: '+91 98765 43213',
    leadBusiness: 'Kovai Organic Foods',
    scheduledAt: '2026-08-10T14:00:00Z',
    followupNumber: 1,
    status: 'pending',
    messageTemplate: 'Hello Karthik! Sent the website design quotation to your email. Excited to build Kovai Organic Foods corporate site!',
    temperature: 'hot',
    createdAt: '2026-08-09T19:10:00Z',
  },
  {
    id: 'fol-3',
    leadId: 'lead-2',
    leadName: 'Priya Sundaram',
    leadPhone: '+91 98765 43211',
    leadBusiness: 'Priya Luxe Hair & Beauty Salon',
    scheduledAt: '2026-08-11T11:30:00Z',
    followupNumber: 2,
    status: 'pending',
    messageTemplate: 'Hi Priya, sharing some recent Website Redesign samples from our portfolio: https://santhosh-portfolio-gamma.vercel.app/',
    temperature: 'warm',
    createdAt: '2026-08-09T16:30:00Z',
  },
  {
    id: 'fol-4',
    leadId: 'lead-5',
    leadName: 'Meena Jayaram',
    leadPhone: '+91 98765 43214',
    leadBusiness: 'Salem Silk Exports',
    scheduledAt: '2026-08-11T16:00:00Z',
    followupNumber: 1,
    status: 'pending',
    messageTemplate: 'Hello Meena, following up on your inquiry about upgrading Salem Silk Exports legacy website to a high-speed React/Next.js site.',
    temperature: 'warm',
    createdAt: '2026-08-09T12:00:00Z',
  },
  {
    id: 'fol-5',
    leadId: 'lead-8',
    leadName: 'Vijay Anand',
    leadPhone: '+91 98765 43217',
    leadBusiness: 'Nellai Spices & Grocery',
    scheduledAt: '2026-08-12T09:30:00Z',
    followupNumber: 1,
    status: 'pending',
    messageTemplate: 'Hi Vijay, did you get a chance to look at our landing page layout options for Nellai Spices?',
    temperature: 'warm',
    createdAt: '2026-08-09T17:50:00Z',
  },
];

export const MOCK_BUSINESS_SETTINGS: BusinessSettings = {
  businessName: BUSINESS_INFO.name,
  description: BUSINESS_INFO.description,
  services: [...BUSINESS_INFO.services],
  serviceArea: BUSINESS_INFO.serviceArea,
  website: BUSINESS_INFO.website,
  email: BUSINESS_INFO.email,
  whatsappNumber: BUSINESS_INFO.whatsapp,
  aiInstructions: DEFAULT_AI_INSTRUCTIONS,
  autoReplyEnabled: true,
  maxFollowups: 3,
  followupIntervalHours: 24,
};

export const MOCK_ANALYTICS_DATA = {
  totalLeads: 1248,
  contactedPercentage: 68.1,
  replyPercentage: 40.2,
  hotLeadPercentage: 12.6,
  conversionPercentage: 5.1,
  monthlyPerformance: [
    { month: 'May', leads: 220, contacted: 180, hot: 12, converted: 4 },
    { month: 'Jun', leads: 340, contacted: 290, hot: 18, converted: 8 },
    { month: 'Jul', leads: 410, contacted: 350, hot: 28, converted: 14 },
    { month: 'Aug (Cur)', leads: 278, contacted: 210, hot: 43, converted: 18 },
  ],
  categoryBreakdown: [
    { category: 'Textile & Retail', count: 420, percentage: 33.6 },
    { category: 'Beauty & Wellness', count: 280, percentage: 22.4 },
    { category: 'Food & Agriculture', count: 230, percentage: 18.4 },
    { category: 'Automobile & Spares', count: 180, percentage: 14.4 },
    { category: 'IT & Others', count: 138, percentage: 11.2 },
  ],
  temperatureDistribution: {
    hot: { count: 43, percentage: 12.6, label: '🔥 HOT Leads (Ready to buy/call)' },
    warm: { count: 185, percentage: 54.1, label: '⚡ WARM Leads (Interested/Inquiring)' },
    cold: { count: 420, percentage: 33.3, label: '❄️ COLD Leads (No reply/Not interested)' },
  },
};
